
# Candace Savonen Sept 2022

name: Render website

on:
  workflow_dispatch:
  push:
    branches: [ main, staging ]
    paths:
      - '**.Rmd'

jobs:
  render-website:
    name: Render website
    runs-on: ubuntu-latest
    container:
      image: rocker/r-rmd

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Run site rendering
      - name: Run bookdown render
        id: bookdown
        run: |
          Rscript -e "rmarkdown::render_site()"

      # Commit the rendered html files
      - name: Commit rendered html files
        run: |
          git add --force *.html
          git commit -m 'Render website' || echo "No changes to commit"
          git pull --allow-unrelated-histories --strategy-option=ours
          git push origin main || echo "No changes to push"
